services:
  - type: web
    name: crypto-news-bot
    runtime: python
    buildCommand: ""
    startCommand: python main.py
    plan: free
    envVars:
      - key: TOKEN
        value: 7853715186:AAEQ0UoMHrQFUu3owEXvctUTOxBPS0mBMwI
      - key: CHANNEL_HANDLE
        value: '@CryptoNewsForFriends'
